# Generated by Django 3.2.7 on 2021-09-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(db_table='stores_products', related_name='stores', to='main_app.Product'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='orders_details',
        ),
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.AlterModelTable(
            name='store',
            table='stores',
        ),
    ]
